export type MetricDirection = "higher_positive" | "higher_negative" | "neutral";
export type MetricCategory =
  | "future"
  | "experience"
  | "activation"
  | "cognition"
  | "social"
  | "risk"
  | "achievement";

export type CoreMetric = {
  slug: string;
  name: string;
  shortName: string;
  question: string;
  lowLabel: string;
  highLabel: string;
  category: MetricCategory;
  direction: MetricDirection;
  snapshotEnabled: boolean;
  dailyEnabled: boolean;
};

export const coreMetrics: readonly CoreMetric[] = [
  {
    slug: "future_wanting",
    name: "Хочу своего будущего",
    shortName: "Будущее",
    question:
      "Насколько меня сейчас эмоционально тянет к собственному будущему?",
    lowLabel: "Будущее вообще не притягивает",
    highLabel: "Очень хочется двигаться вперёд",
    category: "future",
    direction: "higher_positive",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "anticipation",
    name: "Предвкушение",
    shortName: "Предвкушение",
    question: "Насколько я предвкушаю ближайшие часы, дни или события?",
    lowLabel: "Ничего особенно не жду",
    highLabel: "Очень хочется, чтобы будущее наступило",
    category: "future",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "tomorrow_anticipation",
    name: "Насколько мне хочется завтрашнего дня?",
    shortName: "Завтра",
    question: "Насколько мне хочется наступления следующего дня?",
    lowLabel: "Совершенно не хочется",
    highLabel: "Очень хочется проснуться завтра",
    category: "future",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "current_pleasure",
    name: "Удовольствие сейчас",
    shortName: "Удовольствие",
    question: "Насколько приятен текущий момент?",
    lowLabel: "Совсем не приятно",
    highLabel: "Очень приятно",
    category: "experience",
    direction: "higher_positive",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "life_interest",
    name: "Интерес к жизни",
    shortName: "Интерес",
    question: "Насколько интересно жить и смотреть, что происходит дальше?",
    lowLabel: "Совершенно неинтересно",
    highLabel: "Очень интересно",
    category: "experience",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "energy",
    name: "Энергия",
    shortName: "Энергия",
    question: "Сколько сейчас физической и психической энергии?",
    lowLabel: "Сил почти нет",
    highLabel: "Очень много энергии",
    category: "activation",
    direction: "neutral",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "activation",
    name: "Разгон / взвинченность",
    shortName: "Активация",
    question: "Насколько заведено внутреннее состояние?",
    lowLabel: "Полностью спокойно",
    highLabel: "Максимально заведённое состояние",
    category: "activation",
    direction: "neutral",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "anxiety",
    name: "Тревога",
    shortName: "Тревога",
    question: "Насколько сильна тревога?",
    lowLabel: "Полностью спокойно",
    highLabel: "Максимально сильная тревога",
    category: "experience",
    direction: "higher_negative",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "irritability",
    name: "Раздражительность",
    shortName: "Раздражение",
    question: "Насколько сильна раздражительность?",
    lowLabel: "Почти ничего не раздражает",
    highLabel: "Крайне раздражённое состояние",
    category: "experience",
    direction: "higher_negative",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "emotional_intensity",
    name: "Эмоциональная яркость",
    shortName: "Яркость",
    question: "Насколько ярко ощущаются эмоции?",
    lowLabel: "Эмоции почти отсутствуют",
    highLabel: "Чрезвычайно яркие эмоции",
    category: "activation",
    direction: "neutral",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "thought_speed",
    name: "Скорость мыслей",
    shortName: "Мысли",
    question: "Как ощущается скорость мышления?",
    lowLabel: "Очень медленно",
    highLabel: "Очень ускоренно",
    category: "cognition",
    direction: "neutral",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "concentration",
    name: "Концентрация",
    shortName: "Фокус",
    question: "Насколько устойчиво получается сосредоточиться?",
    lowLabel: "Почти невозможно",
    highLabel: "Глубокая стабильная концентрация",
    category: "cognition",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "impulsivity",
    name: "Импульсивность",
    shortName: "Импульсивность",
    question: "Насколько хочется действовать импульсивно?",
    lowLabel: "Решения полностью контролируемые",
    highLabel: "Очень сильный импульс действовать",
    category: "activation",
    direction: "higher_negative",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "social_drive",
    name: "Желание общаться",
    shortName: "Общение",
    question: "Насколько хочется общения?",
    lowLabel: "Хочется полной изоляции",
    highLabel: "Очень хочется общения",
    category: "social",
    direction: "neutral",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "mastery",
    name: "Ощущение прогресса",
    shortName: "Прогресс",
    question:
      "Насколько сегодня я чувствовал, что смог что-то улучшить или освоить?",
    lowLabel: "Нет чувства достижения",
    highLabel: "Сильное чувство роста",
    category: "achievement",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "pride",
    name: "Гордость собой",
    shortName: "Гордость",
    question: "Насколько я горжусь собой сегодня?",
    lowLabel: "Никакой гордости",
    highLabel: "Очень сильная гордость",
    category: "achievement",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "escape_urge",
    name: "Хочется сбежать от реальности",
    shortName: "Эскапизм",
    question: "Насколько хочется уйти от настоящего в стимуляцию?",
    lowLabel: "Не хочется избегать настоящего",
    highLabel: "Максимальное желание отвлекаться",
    category: "experience",
    direction: "higher_negative",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "derealization",
    name: "Дереализация / диссоциация",
    shortName: "Отстранённость",
    question: "Насколько нереальным или отстранённым ощущается состояние?",
    lowLabel: "Всё ощущается обычно",
    highLabel: "Очень сильная нереальность",
    category: "experience",
    direction: "higher_negative",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "death_thoughts",
    name: "Мысли о смерти",
    shortName: "Мысли о смерти",
    question: "Насколько выражены мысли о смерти?",
    lowLabel: "Нет",
    highLabel: "Очень выраженные или навязчивые",
    category: "risk",
    direction: "higher_negative",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "self_harm_urge",
    name: "Желание причинить себе вред",
    shortName: "Самоповреждение",
    question: "Насколько сильно желание причинить себе вред?",
    lowLabel: "Нет",
    highLabel: "Очень сильное желание",
    category: "risk",
    direction: "higher_negative",
    snapshotEnabled: true,
    dailyEnabled: true,
  },
  {
    slug: "goal_drive",
    name: "Желание добиваться целей",
    shortName: "Цели",
    question: "Насколько сильно стремление к достижению результата?",
    lowLabel: "Нет тяги к целям",
    highLabel: "Очень сильное стремление",
    category: "achievement",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
  {
    slug: "general_mood",
    name: "Общее настроение",
    shortName: "Настроение",
    question: "Каково общее настроение?",
    lowLabel: "Очень плохое",
    highLabel: "Очень хорошее",
    category: "experience",
    direction: "higher_positive",
    snapshotEnabled: false,
    dailyEnabled: true,
  },
] as const;

export const metricBySlug = new Map(
  coreMetrics.map((metric) => [metric.slug, metric]),
);
export const snapshotMetrics = coreMetrics.filter(
  (metric) => metric.snapshotEnabled,
);
